space:
  slug: "task_n1k-4"
  server: "http://localhost:8080/kinetic"
  user:
    username: "user@kineticdata.com"
    password: "password"

config_user:
  username: "admin"
  password: "admin"

db:
  server:
    host: "localhost"
    port: "5432"
  user:
    username: "taskadmin"
    password: "TaskPass1"

engine:
  delay: "10"
  threads: "1"
  trigger: "'Selection Criterion'=null"
