################################################################################
#
# Kinetic Data - OpenJDK 8
#
# HOW TO BUILD
# docker build -t kineticdata/openjdk:8u102 -t kineticdata/openjdk:8 -t kineticdata/openjdk:latest .
#
################################################################################

FROM openjdk:8-jdk
MAINTAINER Kinetic Support <support@kineticdata.com>
